version: '3.8'

services:
  # IO Workers
  io-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SHARED_TMP_PATH=/tmp/shared/tasks
    volumes:
      - shared_storage:/tmp/shared
      - ./src:/app/src
    networks:
      - task_network
    command: /app/.venv/bin/celery -A src.core.celery_app worker -Q io -c 20 -n io-worker@%h
    deploy:
      replicas: 1

  # CPU Workers (Classification)
  cpu-classify-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SHARED_TMP_PATH=/tmp/shared/tasks
    volumes:
      - shared_storage:/tmp/shared
      - ./src:/app/src
    networks:
      - task_network
    command: /app/.venv/bin/celery -A src.core.celery_app worker -Q cpu -c 10 -n cpu-classify@%h
    deploy:
      replicas: 1

  # CPU Workers (Encoding)
  cpu-encode-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SHARED_TMP_PATH=/tmp/shared/tasks
    volumes:
      - shared_storage:/tmp/shared
      - ./src:/app/src
    networks:
      - task_network
    command: /app/.venv/bin/celery -A src.core.celery_app worker -Q cpu -c 10 -n cpu-encode@%h
    deploy:
      replicas: 1

volumes:
  shared_storage:

networks:
  task_network:
    external: true
    name: task_network